name = "Notmuch"
uuid = "d7f1370c-97eb-42e0-aeca-99e1e4c4e839"
authors = ["Gregor Kappler"]
version = "0.1.0"

[deps]
AbstractTrees = "1520ce14-60c1-5f80-bbc7-55ef81b5835c"
AutoHashEquals = "15f4f7f2-30c1-5605-9d31-71845cf9641f"
CombinedParsers = "5ae71ed2-6f8a-4ed1-b94f-e14e8158f19e"
DataFrames = "a93c6f00-e57d-5684-b7b6-d8193f3e46c0"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
Inflector = "6d011eab-0732-4556-8808-e463c76bf3b6"
JSON3 = "0f8b85d8-7281-11e9-16c2-39a750bddbf1"
Literate = "98b081ad-f1c9-55d3-8b20-4c87d4299306"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"
LoggingExtras = "e6f89c97-d47a-5376-807f-9c37f3926c36"
MbedTLS = "739be429-bea8-5141-9913-cc70e7f3736d"
Parameters = "d96e819e-fc66-5662-9728-84c9c7592b0a"
PrettyTables = "08abe8d2-0d0c-5749-adfa-8a2ac140af0d"
ReplMaker = "b873ce64-0db9-51f5-a568-4457d8e49576"
SMTPClient = "c35d69d1-b747-5018-a192-25bc5e63c83d"
StyledStrings = "f489334b-da3d-4c2e-b8f0-e476e12c162b"
TextParse = "e0df1984-e451-5cb5-8b61-797a481e67e3"

[compat]

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
